In [2]:
import pandas as pd
import numpy as np
import matplotlib as mp

In [4]:
data =  pd.read_csv("dog_adoption_master.csv")
data.head(10)

,adoption_id,age_years,size,weight_kg,breed_group,intake_type,days_in_shelter,previously_returned,medical_needs,neutered,...,adopter_activity_level,visits_before_adoption,met_resident_pets,adoption_counseling,expectation_score,energy_mismatch,size_home_mismatch,return_reason,days_to_return,returned
0,ADP000000,2.6,small,7.2,mixed,stray,51,0,none,1,...,2.6,1,0,0,7.3,1.4,0,kept,NaN,0
1,ADP000001,5.4,large,27.9,sporting,stray,38,1,none,1,...,3.8,1,0,0,6.2,4.2,0,kept,NaN,0
2,ADP000002,3.5,medium,15.4,mixed,owner_surrender,14,0,none,1,...,1.1,1,0,0,8.1,3.5,0,kept,NaN,0
3,ADP000003,7.3,medium,23.2,working,stray,9,0,none,1,...,7.8,3,0,1,10.0,0.8,0,unmet_expectations,4.5,1
4,ADP000004,0.7,medium,16.2,mixed,stray,35,1,minor,1,...,3.6,1,0,0,7.9,6.4,0,aggression,12.9,1
5,ADP000005,4.9,medium,14.5,working,stray,44,0,none,1,...,6.1,2,1,1,6.6,0.4,0,kept,NaN,0
6,ADP000006,6.8,medium,19.4,herding,stray,27,0,none,1,...,5.1,3,0,0,5.0,0.7,0,kept,NaN,0
7,ADP000007,4.7,large,30.6,working,owner_surrender,7,0,none,1,...,5.6,1,0,0,5.2,0.7,0,kept,NaN,0
8,ADP000008,4.4,large,25.2,mixed,stray,20,0,none,1,...,3.5,1,0,0,8.2,5.9,1,kept,NaN,0
9,ADP000009,4.9,small,8.7,terrier,stray,40,0,minor,1,...,5.0,1,0,0,5.2,0.3,0,kept,NaN,0

In [5]:
data.isnull().sum()

adoption_id                   0
age_years                     0
size                          0
weight_kg                     0
breed_group                   0
intake_type                   0
days_in_shelter               0
previously_returned           0
medical_needs                 0
neutered                      0
aggression_score              0
anxiety_separation            0
reactivity_to_dogs            0
energy_level                  0
training_level                0
house_trained                 0
first_time_owner              0
household_has_kids            0
household_has_pets            0
home_type                     0
has_yard                      0
hours_alone_per_day           0
adopter_activity_level        0
visits_before_adoption        0
met_resident_pets             0
adoption_counseling           0
expectation_score             0
energy_mismatch               0
size_home_mismatch            0
return_reason                 0
days_to_return            35703
returned                      0
dtype: int64

In [7]:
data.shape

(42000, 32)